kind: pipeline
name: deploy

steps:
  - name: unit-test
    image: hashicorp/terraform:0.11.14
    environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - terraform plan
    when:
      branch: v4
      event: push
