version: "2"
services:
  mongo:
    image: "mongo"
    volumes:
      - ./data:/data
    ports:
      - "27017"
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "9000:9000"
    environment:
      - "token=bea376cb4ed3daad21e16d0bc25bd281"
